version: '3.8'

services:
 rabbitmq:
   image: rabbitmq:3-management
   container_name: local-rabbit
   ports: 
     - "5672:5672"
     - "15672:15672"
   environment:
     - RABBITMQ_DEFAULT_USER=ceastin
     - RABBITMQ_DEFAULT_PASS=sahilsri
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq

volumes: 
 rabbitmq_data:
